# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/dsd/new3_proj/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/dsd/new3_proj/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.5 [current_project]
set_property ip_output_repo e:/dsd/new3_proj/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/dsd/cnn_open-master/cnn_open-master/model/bhvsram/bhv_1w1r_sram.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/global.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/capture.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/cnn.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/draw_rectangle.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/lenet.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/lenet_roms.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/misc.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/osd.sv
  E:/dsd/cnn_open-master/cnn_open-master/model/xilinx/xilinx_1w1r_sram.sv
  E:/dsd/cnn_open-master/cnn_open-master/model/xilinx/xilinx_srams.sv
  E:/dsd/cnn_open-master/cnn_open-master/src/lenet_top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xcku040-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
